const OFFER_PENDING_REQUEST = 0
const OFFER_ACCEPTED_FOR_REQUEST = 1
const OFFER_DENIED = 2

const REQUEST_WITH_PENDING_OFFERS = 0
const REQUEST_WITH_OFFER_SELECTED = 1

module.exports = {
	OFFER_PENDING_REQUEST,
	OFFER_ACCEPTED_FOR_REQUEST,
	OFFER_DENIED,
	REQUEST_WITH_PENDING_OFFERS,
	REQUEST_WITH_OFFER_SELECTED,
}